from typing import Dict, List

from app.threats.schemas import MitreMapping, ThreatRuleSchema


RULES: List[ThreatRuleSchema] = [
    ThreatRuleSchema(
        rule_name="SQL Injection",
        description="Detects patterns commonly used in SQL injection payloads and query manipulation.",
        severity="critical",
        category="Injection",
        confidence=95,
        priority="P1",
        mitre=MitreMapping(
            technique="SQL Injection",
            technique_id="T1190",
            tactic="Initial Access",
            description="Adversaries may abuse SQL injection to execute unauthorized database queries.",
            reference="https://attack.mitre.org/techniques/T1190/",
        ),
        recommended_action="Validate and sanitize database inputs, apply parameterized queries, and block unsafe SQL patterns.",
    ),
    ThreatRuleSchema(
        rule_name="Cross Site Scripting (XSS)",
        description="Detects script injection or payloads that can execute in user browsers.",
        severity="high",
        category="Injection",
        confidence=90,
        priority="P2",
        mitre=MitreMapping(
            technique="Cross-Site Scripting",
            technique_id="T1059.007",
            tactic="Execution",
            description="Adversaries may inject scripts that execute in another user's browser.",
            reference="https://attack.mitre.org/techniques/T1059/007/",
        ),
        recommended_action="Escape HTML output, validate inputs, and enforce Content Security Policy headers.",
    ),
    ThreatRuleSchema(
        rule_name="Command Injection",
        description="Detects command syntax and dangerous shell operator usage in user-controlled content.",
        severity="critical",
        category="Execution",
        confidence=94,
        priority="P1",
        mitre=MitreMapping(
            technique="Command and Scripting Interpreter",
            technique_id="T1059",
            tactic="Execution",
            description="Adversaries may execute arbitrary commands through vulnerable command interpreters.",
            reference="https://attack.mitre.org/techniques/T1059/",
        ),
        recommended_action="Avoid shell execution of user input and use strong validation or allowlists.",
    ),
    ThreatRuleSchema(
        rule_name="Prompt Injection",
        description="Detects attempts to override or manipulate AI model instructions through crafted input.",
        severity="high",
        category="AI Manipulation",
        confidence=92,
        priority="P2",
        mitre=MitreMapping(
            technique="Manipulation of Input",
            technique_id="T1529",
            tactic="Impact",
            description="Adversaries may attempt to manipulate AI or automation inputs to alter behavior.",
            reference="https://attack.mitre.org/techniques/T1529/",
        ),
        recommended_action="Use prompt hygiene, remove unauthorized instructions, and validate model inputs before use.",
    ),
    ThreatRuleSchema(
        rule_name="Phishing URL",
        description="Detects suspicious URLs that mimic trusted domains or carry phishing indicators.",
        severity="high",
        category="Social Engineering",
        confidence=88,
        priority="P2",
        mitre=MitreMapping(
            technique="Phishing",
            technique_id="T1566",
            tactic="Initial Access",
            description="Adversaries may use phishing URLs to trick victims into providing credentials or executing malware.",
            reference="https://attack.mitre.org/techniques/T1566/",
        ),
        recommended_action="Block suspicious domains, validate URL reputation, and enforce email/URL filtering.",
    ),
    ThreatRuleSchema(
        rule_name="Malware Indicator",
        description="Detects known malicious file names, process names, or delivery patterns.",
        severity="critical",
        category="Malware",
        confidence=90,
        priority="P1",
        mitre=MitreMapping(
            technique="Malware",
            technique_id="T1204",
            tactic="Execution",
            description="Adversaries may deliver and execute malware with suspicious artifacts.",
            reference="https://attack.mitre.org/techniques/T1204/",
        ),
        recommended_action="Quarantine suspicious files and block known malware indicators.",
    ),
    ThreatRuleSchema(
        rule_name="Credential Leakage",
        description="Detects exposed credentials, tokens, or secrets in text or logs.",
        severity="high",
        category="Data Exposure",
        confidence=87,
        priority="P2",
        mitre=MitreMapping(
            technique="Credentials in Files",
            technique_id="T1552",
            tactic="Credential Access",
            description="Adversaries may access exposed credentials stored in plaintext.",
            reference="https://attack.mitre.org/techniques/T1552/",
        ),
        recommended_action="Mask credentials, rotate secrets, and audit storage for exposed secrets.",
    ),
    ThreatRuleSchema(
        rule_name="Reverse Shell Detection",
        description="Detects command patterns typically used for reverse shell creation.",
        severity="critical",
        category="Network",
        confidence=93,
        priority="P1",
        mitre=MitreMapping(
            technique="Remote File Copy",
            technique_id="T1105",
            tactic="Command and Control",
            description="Adversaries may use reverse shell commands to establish remote access.",
            reference="https://attack.mitre.org/techniques/T1105/",
        ),
        recommended_action="Block outbound command shell traffic and restrict interpreter execution.",
    ),
    ThreatRuleSchema(
        rule_name="Encoded Payload Detection",
        description="Detects common obfuscation techniques such as base64, URL encoding, and escape sequences.",
        severity="high",
        category="Obfuscation",
        confidence=86,
        priority="P2",
        mitre=MitreMapping(
            technique="Obfuscated Files or Information",
            technique_id="T1027",
            tactic="Defense Evasion",
            description="Adversaries may hide payloads using encoding or obfuscation.",
            reference="https://attack.mitre.org/techniques/T1027/",
        ),
        recommended_action="Decode suspicious payloads and block obfuscation patterns in input data.",
    ),
    ThreatRuleSchema(
        rule_name="Directory Traversal",
        description="Detects path traversal patterns that may expose filesystem resources.",
        severity="high",
        category="Access Abuse",
        confidence=90,
        priority="P2",
        mitre=MitreMapping(
            technique="Path Traversal",
            technique_id="T1059.006",
            tactic="Execution",
            description="Adversaries may traverse directories to access unexpected files.",
            reference="https://attack.mitre.org/techniques/T1059/006/",
        ),
        recommended_action="Normalize and validate file paths, and restrict access to authorized directories.",
    ),
    ThreatRuleSchema(
        rule_name="Ransomware Indicator",
        description="Detects ransomware-related keywords, known encryptor behaviors, or extortion patterns.",
        severity="critical",
        category="Ransomware",
        confidence=92,
        priority="P1",
        mitre=MitreMapping(
            technique="Data Encrypted for Impact",
            technique_id="T1486",
            tactic="Impact",
            description="Adversaries may encrypt data in order to extort victims.",
            reference="https://attack.mitre.org/techniques/T1486/",
        ),
        recommended_action="Detect suspicious encryption activity and isolate impacted hosts immediately.",
    ),
    ThreatRuleSchema(
        rule_name="Suspicious File Extension",
        description="Detects high-risk file extensions associated with malware or executable payloads.",
        severity="medium",
        category="File System",
        confidence=82,
        priority="P3",
        mitre=MitreMapping(
            technique="User Execution",
            technique_id="T1204",
            tactic="Execution",
            description="Adversaries may use dangerous executable files to compromise systems.",
            reference="https://attack.mitre.org/techniques/T1204/",
        ),
        recommended_action="Block or scan dangerous file extensions before execution.",
    ),
    ThreatRuleSchema(
        rule_name="Dangerous HTTP Header",
        description="Detects suspicious HTTP headers used for host header injection, cache poisoning, or request smuggling.",
        severity="medium",
        category="Network",
        confidence=78,
        priority="P3",
        mitre=MitreMapping(
            technique="Exploitation of Remote Services",
            technique_id="T1210",
            tactic="Privilege Escalation",
            description="Adversaries may abuse malformed headers to exploit remote services.",
            reference="https://attack.mitre.org/techniques/T1210/",
        ),
        recommended_action="Validate and sanitize incoming headers, and reject malformed requests.",
    ),
    ThreatRuleSchema(
        rule_name="Suspicious User Agent",
        description="Detects unusual or known malicious user agent strings used in reconnaissance and attacks.",
        severity="low",
        category="Reconnaissance",
        confidence=75,
        priority="P4",
        mitre=MitreMapping(
            technique="Network Service Scanning",
            technique_id="T1595",
            tactic="Discovery",
            description="Adversaries may use suspicious user agents during scanning and reconnaissance.",
            reference="https://attack.mitre.org/techniques/T1595/",
        ),
        recommended_action="Monitor and block anomalous user agents in traffic logs.",
    ),
]


RULE_MAP: Dict[str, ThreatRuleSchema] = {rule.rule_name: rule for rule in RULES}
